### ISSUE TITLE
Error on missing API key

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot-ai-editor#45]
Testing this via the GitHub Actions workflow, and the workflow passes without providing an Open AI API key secret.

This shows up in the PR diff as an HTML comment:

```
<!--
ERROR: the paragraph below could not be revised with the AI model due to the following error:
You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.
-->
```

So, the user will (hopefully) catch the error there, but I can imagine many users forgetting to do this and it'd be nice to "fail faster". The workflow should probably fail so it can show the user a big ❌  right away.

Also, the HTML comment above seems like an error message from Open AI. It'd be nice to show our own more plain-language error.

Not sure if this issue belongs here or in the `manubot` repo. I think this package would be the place to throw the error, and hopefully the `manubot` CLI wrapper calling it would catch and report the error appropriately.

**Comment by falquaddoomi** [comment]
The code that's supposed to handle a missing OpenAI API key is here: https://github.com/manubot/manubot-ai-editor/blob/main/libs/manubot_ai_editor/models.py#L146-L154. I believe the AI revision GitHub workflow sets the env var `OPENAI_API_KEY` to an empty string rather than not setting it at all, and that check only checks if it's `None`.

Anyway, here's the relevant PR that fixes it: #46. Feel free to test it and see if you're seeing the workflow fail; it should, since I don't see anything in the manubot ai_revision CLI wrapper, https://github.com/manubot/manubot/blob/main/manubot/ai_revision/ai_revision_command.py#L41-L54, that catches exceptions thrown on model instantiation.
